### ISSUE TITLE
ImportError: cannot import name 'GoalEnv' from 'gym.core'

### ISSUE THREAD

**Issue by quantitative-technologies** [mymusise/Trading-Gym#3]
I get this  from the code:

    >>> from trading_gym.env import TradeEnv

What should I do?

**Comment by mymusise** [comment]
Which version of python are you running?
Is there any error when you install it?

**Comment by quantitative-technologies** [comment]
I am using Python 3.8.2.

However, I just installed a fresh virtual environment and installed Trading-Gym, and everything seems fine.

I don't know how to reproduce the above error. Sorry for the confusion.

**Comment by mymusise** [comment]
I just test it python 3.8.2 and it work.

![image](https://user-images.githubusercontent.com/6883957/85403377-d06d5b80-b58f-11ea-99b3-4e38e18b7fb7.png)

Try to reinstall in another fresh virtual environment bro.

**Comment by quantitative-technologies** [comment]
Yes, that it what I meant. It worked fine for me too with a fresh virtual env.

I can close this issue if you like. Thanks.
